// apps/web/atlas-web/components/ui/input.tsx
import * as React from "react";

import { cn } from "@/lib/utils";

const Input = React.forwardRef<HTMLInputElement, React.InputHTMLAttributes<HTMLInputElement>>(
  ({ className, type, ...props }, ref) => (
    <input
      type={type}
      className={cn(
        "flex h-12 w-full rounded-2xl border border-[var(--atlas-ink)]/20 bg-white px-4 text-sm text-[var(--atlas-ink)] placeholder:text-[var(--atlas-ink-muted)] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[var(--atlas-accent)]",
        className
      )}
      ref={ref}
      {...props}
    />
  )
);
Input.displayName = "Input";

export { Input };

// src/components/ui/input/Input.vue
<script setup lang="ts">
import { computed, useAttrs } from "vue";
import { cn } from "../../../lib/utils";

const props = defineProps<{
  modelValue?: string | number;
}>();

const emit = defineEmits<{
  (event: "update:modelValue", value: string | number): void;
}>();

const attrs = useAttrs();
const classes = computed(() =>
  cn(
    "flex h-10 w-full rounded-md border border-input bg-transparent px-3 py-2 text-sm text-foreground placeholder:text-muted-foreground focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring disabled:cursor-not-allowed disabled:opacity-50",
    attrs.class
  )
);

function onInput(event: Event) {
  const target = event.target as HTMLInputElement;
  if (target.type === "number") {
    emit("update:modelValue", target.value === "" ? "" : target.valueAsNumber);
    return;
  }
  emit("update:modelValue", target.value);
}
</script>

<template>
  <input v-bind="attrs" :class="classes" :value="modelValue" @input="onInput" />
</template>
