// apps/web/components/ui/input.tsx
import * as React from "react"

import { cn } from "@/lib/utils"

function Input({ className, type, ...props }: React.ComponentProps<"input">) {
  return (
    <input
      type={type}
      data-slot="input"
      className={cn(
        "file:text-foreground placeholder:text-muted-foreground selection:bg-primary selection:text-primary-foreground border-[hsl(var(--border)/0.85)] h-9 w-full min-w-0 rounded-md bg-[var(--atlas-surface-soft)] px-3 py-1 text-base shadow-[var(--atlas-shadow-glass)] backdrop-blur-sm transition-[color,box-shadow] outline-none file:inline-flex file:h-7 file:border-0 file:bg-transparent file:text-sm file:font-medium disabled:pointer-events-none disabled:cursor-not-allowed disabled:opacity-50 md:text-sm",
        "focus-visible:border-ring focus-visible:ring-ring/50 focus-visible:ring-[3px]",
        "aria-invalid:ring-destructive/20 dark:aria-invalid:ring-destructive/40 aria-invalid:border-destructive",
        className
      )}
      {...props}
    />
  )
}

export { Input }

// src/components/ui/input/Input.vue
<script setup lang="ts">
import { computed, useAttrs } from "vue";
import { cn } from "../../../lib/utils";

const props = defineProps<{
  modelValue?: string | number;
}>();

const emit = defineEmits<{
  (event: "update:modelValue", value: string | number): void;
}>();

const attrs = useAttrs();
const classes = computed(() =>
  cn(
    "flex h-10 w-full rounded-md border border-input bg-transparent px-3 py-2 text-sm text-foreground placeholder:text-muted-foreground focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring disabled:cursor-not-allowed disabled:opacity-50",
    attrs.class
  )
);

function onInput(event: Event) {
  const target = event.target as HTMLInputElement;
  if (target.type === "number") {
    emit("update:modelValue", target.value === "" ? "" : target.valueAsNumber);
    return;
  }
  emit("update:modelValue", target.value);
}
</script>

<template>
  <input v-bind="attrs" :class="classes" :value="modelValue" @input="onInput" />
</template>
